name: encodedgdumb
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - pandas
  - ca-certificates
  - certifi
  - openssl
  - plotly
  - nbformat
  - python-kaleido
  - matplotlib
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
